[mysql]
debug = "true"
type = "mysql"
hostname = "127.0.0.1"
database = "jingbanyun"
username = "root"
password = "123456"
hostport = "3306"
dsn = ""
charset = "utf-8"
prefix = ""

[web]
debug = "true"

[runtime]
file = "E:/goroot/src/penghui.com/runtime/errors.log"

[token]
token = "jingbanyun.com"