package setslice

var ImportInfo string = "/api/company/importInfo?"
var LicenseInfo string = "/api/company/updateAdminLicenseInfo?"
var UpdateAppInfo string = "/api/company/updateAppInfo?"
var UpdateAppClass string = "/api/company/updateAppClass?"
var UpdateDishonest string = "/api/company/updateDishonestInformationInfo?"
var UpdateAbnormal string = "/api/company/updateAbnormalOperInfo?"
var UpdateJudicial string = "/api/company/updateJudicialLitigationInfo?"
var UpdateSafeScanInfo string = "/api/company/updateSafeScanInfo?"
var UserFeed string = "/api/user/addUserFeedbackInfo?"
var UpdateInfo string = "/api/company/updateInfo?"
var AppCommentInfo string = "/api/company/addAppCommentInfo?"
var AddCourseInfo string = "/api/course/addCourseInfo?"
var AddOrderInfo string = "/api/user/addOrderInfo?"
var UpdateUserFeedbackInfo string = "/api/user/updateUserFeedbackInfo?"
var AddTeacherInfo string = "/api/user/AddTeacherInfo?"
var AddUserLoginInfo string = "/api/user/AddUserLoginInfo?"
var AddOnlineTimeInfo string = "/api/user/addOnlineTimeInfo?"
var AddStudentInfo string = "/api/user/addStudentInfo?"
var AddParentInfo string = "/api/user/addParentInfo?"
var AddAuthInfo string = "/api/user/addAuthInfo?"
var TestHttp string = "/api/user/TestHttp?"
var DoHttp string = "http://bigdata3.jtypt.com/?s=/api/Etl/dayEtl"
